### ISSUE TITLE
Cutoff edge cases - nan and infinite

### ISSUE THREAD

**Issue by PicoCentauri** [Luthaf/vesin#22]
- If the `cutoff` is not a number (`torch.nan`) there is a segfault.
- If the `cutoff` is not finite (`torch.inf`), I think we end up again in an infinite loop

Might be worth to catch these two cases before one runs into these problems as user. Not urgent though

**Comment by Luthaf** [comment]
That should be easy to handle, we need to add a couple more tests around https://github.com/Luthaf/vesin/blob/89dd3133eaf42b6bb8e73bc281b0043469f558a3/vesin/src/vesin.cpp#L39-L42
